// build_options: 
Java Performance Tuning - Benchmarking tools
============================================
Arnauld Van Muysewinkel <avm@pendragon.be>
v0.0, dd-mmm-2015: Draft version
:backend: slidy
//:theme: volnitsky
:data-uri:
:copyright: Creative-Commons-Zero (Arnauld Van Muysewinkel)


Content
-------

* <<_rtri_requirements,Requirements>>
// GUI (heavy client) testing (p38-41)
// Regression testing (p42)
* market overview
// injectors (p37)
// Standard APi testing (p43-44) + Gattling, LoadRunner ...
* jmeter
** basics
// Jmeter ... (pp45...83, 89...97)
** threading model
// Threading model (p84-89)
** timers
** parameters
* Mock-Ups
// (p98-99)
* Practical considerations
** Randomization
// ! _random_ parameters
// ! randomize _before_ run
// randomize timers
** duration
// statistical representativeness
** caching!
// p27-28
** https://regex101.com
* analysing/graphing/reporting...

_(link:../0-extra/1-training_plan.html#_presentations[back to course plan])_


&rtri; Requirements
-------------------

An injector is a tool that is able to _reproducibly_ generate a _well-defined_ load.

* Submit (receive) any kind of HTTP request (response)
* Submit other kind of requests (JDBC, RMI, (SOAP), execute Java code for specific cases)
* Represent complex scenario logic 
* Management of high number of virtual users
* _'Parameterizable'_
* Recording of results

Optional:

* real time display
* analysis, reporting


Kinds of testing tools
----------------------

[type="asciidoc",cols="^10,^1,^10,^1,^10",grid="none",frame="none"]
|=====
|GUI testing
|>
|*Protocol level testing*
|>
|Unit testing
|=====

* GUI testing
** fragile
** e.g. FAT client testing
* *Protocol (or API) level testing*
** HTTP, FTP, SOAP, SMTP, JDBC...
** robust, good isolation level -> best for performance testing
** e.g. web based
* Unit testing = Non-regression testing
** closer to micro-benchmarking
** e.g. JUnit



