// build_options: 
Java Performance Tuning - Training Plan
=======================================
Arnauld Van Muysewinkel <avm@pendragon.be>
v0.1, 24-Sep-2015: Draft version
:backend: slidy
//:theme: volnitsky
:data-uri:
:copyright: Creative-Commons-Zero (Arnauld Van Muysewinkel)
:br: pass:[<br>]


Day 1 - AM
----------

*****
Writing performance tests
*****

* Introduction
* _Workshop 0: install training toolsuite_
* Anatomy of a test
* Benchmarking tool: basics
* _Workshop 1: write your first performance tests_


Day 1 - PM
----------

*****
Writing performance tests (cont'd)
*****

* Planning your test
* Load profiles
* Metrics
* Benchmarking tool: threading model, timers
* Benchmarking tool: parameters
* _Workshop 2: wrap up your performance tests_


Day 2 - AM
----------

*****
Investigating performance issues
*****

* Performance Diagnostic Model (PDM): Introduction{br}&nbsp;
* &target; Reminder about OSes internals (scheduling...)
* PDM: Layer 1 (OS)
* OS Monitoring tools
* _Workshop 3 (interactive): PDM Layer 1 (OS) in practice_


Day 2 - PM
----------

*****
Investigating performance issues (cont'd)
*****

* PDM: Layer 2 (JVM)
* &target; Reminder of some JVM internals (GC, JIT...)
* JVM Monitoring tools
* _Workshop 4 (interactive): PDM Layer 2 (JVM) in practice_


Day 3 - AM
----------

*****
Investigating performance issues (cont'd)
*****

* PDM: Layer 3 (Application)
* Application Monitoring tools
* _Workshop 5 (interactive): PDM Layer 3 (Application) in practice_


Day 3 - PM
----------

*****
Going further
*****

* Performance testing process
* Other analysis tools (RG, Excel, R, ELK...)
* _Workshop 6: Using the Report Generator (beta)_ (?)
// Is it feasible to share the RG with a broader audience?
* Introduction to Hyperion (?)
* JPA performance (?)
* Web front-end performance (?)


Presentations
-------------

* link:../1-intro/0-introduction.html#_content[Introduction]
* link:../1-intro/1-objectives.html#_content[Objectives]
* link:../2-benchmark/1-benchmark_design.html#_content[Designing your benchmarks]
* link:../2-benchmark/2-benchmark_tool.html#_content[Benchmarking tools]
* link:../3-pdm/0-pdm_intro.html#_content[Performance Diagnostic Model (introduction)]
* link:../3-pdm/1-pdm_l1-os.html#_content[PDM Layer 1: Operating System]
* link:../3-pdm/2-pdm_l2-jvm.html#_content[PDM Layer 2: Java Virtual Machine]
* link:../3-pdm/3-pdm_l3-app.html#_content[PDM Layer 3: Application]
* link:../4-process/0-perf_test_process.html#_content[Performance Testing Process]
* link:../5-analysis/1-analysis_tools.html#_content[Analysis Tools]


Workshops
---------

* link:../1-intro/w0-install.html#_content[Install the training toolsuite]
* link:../2-benchmark/w1-first_benchmark.html#_content[First performance test]
* link:../2-benchmark/w2-wrapup_benchmark.html#_content[Wrap-up the performance test]
* link:../3-pdm/w3-dominant_os.html#_content[PDM Layer 1 (OS) in practice]
* link:../3-pdm/w4-dominant_jvm.html#_content[PDM Layer 2 (JVM) in practice]
* link:../3-pdm/w5-dominant_app.html#_content[PDM Layer 3 (Application) in practice]


Extras
------

* link:../0-extra/0-course_description.html#_content[Course Description]
* link:../0-extra/2-internals_os.html#_content[Operating Systems Internals]
* link:../0-extra/3-internals_jvm.html#_content[Java VM Internals]

