// build_options: 
Java Performance Tuning - Training Plan
=======================================
Arnauld Van Muysewinkel <avm@pendragon.be>
v0.1, 24-Sep-2015: Draft version
:backend: slidy
//:theme: volnitsky
:data-uri:
:copyright: Creative-Commons-Zero (Arnauld Van Muysewinkel)

Day 1
-----

*****
Writing performance tests
*****

AM
~~

* Introduction
* _Workshop 0: install training toolsuite_
* Anatomy of a test
* Benchmarking tool: basics
* _Workshop 1: write your first performance tests_

[role="incremental"]
PM
~~

* Planning your test
* Load profiles
* Metrics
* Benchmarking tool: threading model, timers
* Benchmarking tool: parameters
* _Workshop 2: wrap up your performance tests_

Day 2
-----

*****
Investigating performance issues
*****

AM
~~

* Reminder about OSes internals (scheduling...)
* Reminder of some JVM internals (GC, JIT...)
* Performance Diagnostic Model (PDM): Introduction
* PDM: Layer 1 (OS)
* OS Monitoring tools
* _Workshop 3 (interactive): PDM Layer 1 (OS) in practice_

[role="incremental"]
PM
~~

* PDM: Layer 2 (JVM)
* JVM Monitoring tools
* _Workshop 4 (interactive): PDM Layer 2 (JVM) in practice_

Day 3
-----

AM
~~

*****
Investigating performance issues (cont)
*****

* PDM: Layer 3 (Application)
* Application Monitoring tools
* _Workshop 5 (interactive): PDM Layer 3 (Application) in practice_

[role="incremental"]
PM
~~

*****
Going further
*****

* Performance testing process
* Other analysis tools (RG, Excel, R, ELK...)
* _Workshop 6: Using the Report Generator (beta)_ (?)
// Is it feasible to share the RG with a broader audience?
* Introduction to Hyperion (?)
* JPA performance (?)
* Web front-end performance (?)


Presentations
-------------

* link:../1-intro/0-introduction.html[Introduction]
* link:../1-intro/1-objectives.html[Objectives]
* link:../2-benchmark/1-benchmark_design.html[Designing your benchmarks]
* link:../2-benchmark/2-benchmark_tool.html[Benchmarking tools]
* link:../3-pdm/0-pdm_intro.html[Performance Diagnostic Model (introduction)]
* link:../3-pdm/1-pdm_l1-os.html[PDM Layer 1: Operating System]
* link:../3-pdm/2-pdm_l2-os.html[PDM Layer 2: Java Virtual Machine]
* link:../3-pdm/3-pdm_l3-os.html[PDM Layer 3: Application]
* link:../4-process/0-perf_test_process.html[Performance Testing Process]
* link:../5-analysis/1-analysis_tools.html[Analysis Tools]


Presentations
-------------

Workshops
~~~~~~~~~

* link:../1-intro/w0-install.html[Install the training toolsuite]


Extra
~~~~~

* link:../0-extra/0-course_description.html[Course Description]
* link:../0-extra/2-internals_os.html[Operating Systems Internals]
* link:../0-extra/3-internals_jvm.html[Java VM Internals]

